#!/bin/bash
# Simple file transfer helper

echo "=========================================="
echo "Pathlight File Transfer Helper"
echo "=========================================="

echo "✅ Project archive created: /tmp/pathlight_project.tar.gz"
echo "📁 Size: $(ls -lh /tmp/pathlight_project.tar.gz | awk '{print $5}')"
echo ""
echo "📋 Transfer Options:"
echo ""
echo "1️⃣  DIRECT TRANSFER (Recommended):"
echo "   • Safely eject microSD from Mac"
echo "   • Insert microSD into Jetson"
echo "   • On Jetson, run:"
echo "     mkdir -p /home/nvidia/cursorPathlight"
echo "     cd /home/nvidia/cursorPathlight"
echo "     # Then copy files manually or via network"
echo ""
echo "2️⃣  NETWORK TRANSFER:"
echo "   • On Mac: cd /tmp && python3 -m http.server 8000"
echo "   • On Jetson: wget http://[MAC_IP]:8000/pathlight_project.tar.gz"
echo ""
echo "3️⃣  USB TRANSFER:"
echo "   • Copy /tmp/pathlight_project.tar.gz to USB drive"
echo "   • Transfer USB to Jetson"
echo "   • Extract on Jetson"
echo ""
echo "📖 See TRANSFER_GUIDE.md for detailed instructions"
echo ""
echo "🎯 After transfer, on Jetson run:"
echo "   cd /home/nvidia/cursorPathlight"
echo "   chmod +x setup_jetson.sh"
echo "   ./setup_jetson.sh"
echo "   sudo systemctl start pathlight"
